name = "systemsSerology"
uuid = "12d3ff75-5241-45b7-b303-d29cf6c8f34b"
authors = ["Aaron Meyer <a@asmlab.org>", "Cyrillus Tan"]
version = "0.1.0"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Gadfly = "c91e804a-d5a3-530f-b6f0-dfbca275c004"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extras]
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Profile", "Random"]
